### ISSUE TITLE
Node-Svd installation Issue

### ISSUE THREAD

**Issue by partinder** [xionluhnis/node-svd#1]
While installing Node-Svd on Node 0.12.4 it gives the following issue, I got it to work by downgrading the node version.

../svd.cc:167:1: warning: control reaches end of non-void function [-Wreturn-type]

 }

 ^

make: **\* [Release/obj.target/svd/svd.o] Error 1

make: Leaving directory `/home/bitnami/node_modules/node-svd/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/opt/bitnami/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)

gyp ERR! stack     at ChildProcess.emit (events.js:110:17)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

gyp ERR! System Linux 3.13.0-53-generic

gyp ERR! command "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /home/bitnami/node_modules/node-svd

gyp ERR! node -v v0.12.4

gyp ERR! node-gyp -v v1.0.2

gyp ERR! not ok 

npm ERR! Linux 3.13.0-53-generic

npm ERR! argv "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/bin/npm" "i" "node-svd"

npm ERR! node v0.12.4

npm ERR! npm  v2.1.18

npm ERR! code ELIFECYCLE

npm ERR! node-svd@0.1.2 install: `node-gyp rebuild && cp build/Release/svd.node ./svd.node`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the node-svd@0.1.2 install script 'node-gyp rebuild && cp build/Release/svd.node ./svd.node'.

npm ERR! This is most likely a problem with the node-svd package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     node-gyp rebuild && cp build/Release/svd.node ./svd.node

npm ERR! You can get their info via:

npm ERR!     npm owner ls node-svd

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR!     /home/bitnami/npm-debug.log

**Comment by flore2003** [comment]
I fixed this problem in a fork and submitted a pull request for it #2
